import { createStyles } from 'antd-style';

export const useStyles = createStyles({
  header: {
    display: 'grid',
    gridTemplateColumns: '1fr 1.2fr',
    padding: 'var(--x2)',
    alignItems: 'center',
    borderBottom: '1px solid var(--color-gray-3)',
  },
  row: {
    cursor: 'pointer',
    display: 'grid',
    gridTemplateColumns: '1fr 1.2fr',
    padding: 'var(--x2)',
    alignItems: 'center',
    borderBottom: '1px solid var(--color-gray-3)',
    '&:hover': {
      backgroundColor: 'var(--color-gray-2)',
    },
    '&:hover button:first-of-type': {
      backgroundColor: 'var(--color-gray-4)',
    },
  },
  widgetContainer: {
    border: '1px solid var(--color-border)',
    alignItems: 'center',
    backgroundColor: 'var(--color-gray-1)',
    borderRadius: 'var(--radius-base)',
    boxShadow: 'var(--box-shadow-border)',
    boxSizing: 'border-box',
    display: 'flex',
    flexWrap: 'wrap',
    gap: 'var(--x1)',
    minHeight: 40,
    outline: '4px solid transparent',
    padding: 3,
    transition: 'all 0.2s ease',
    width: '100%',
    '&:has(input[data-node-type="ui-filter-search"]:focus)': {
      outlineColor: 'var(--color-gray-4)',
      borderColor: 'var(--color-primary-10)',
    },
  },
  filterNode: {
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    flexShrink: 0,
    overflow: 'hidden',
    backgroundColor: 'var(--color-gray-3)',
    border: '1px solid var(--color-border)',
    borderRadius: 'var(--radius-base)',
    transition: 'all 0.2s ease',
    boxSizing: 'border-box',
    outline: '1px solid transparent',
    '&:focus, &:focus-within': {
      outlineColor: 'var(--color-gray-5)',
      borderColor: 'var(--color-gray-10)',
    },
  },
  filterNodeLeft: {
    padding: '0 var(--x2)',
    height: 30,
    display: 'flex',
    alignItems: 'center',
    backgroundColor: 'transparent',
    transition: 'all 0.2s ease',
  },
  filterNodeCenterWrapper: {
    '--bg': 'var(--color-gray-1)',
    height: 30,
    display: 'flex',
    alignItems: 'center',
    transition: 'all 0.2s ease',
  },
  filterNodeCenter: {
    height: 30,
    display: 'flex',
    alignItems: 'center',
    transition: 'all 0.2s ease',
    background: 'linear-gradient(to right, transparent 49.5%, var(--bg) 50%, var(--bg) 100%)',
  },
  operatorTag: {
    display: 'block',
    minWidth: '30px !important',
    textAlign: 'center',
  },
  filterNodeRight: {
    display: 'flex',
    alignItems: 'center',
    padding: '0 var(--x1)',
    backgroundColor: 'var(--bg)',
    height: 32,
    minWidth: 50,
  },
  searchInput: {
    width: 'unset',
    flexGrow: 1,
  },
  filterLabelButton: {
    textAlign: 'left',
    backgroundColor: 'var(--color-gray-3)',
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--x3)',
  },
  breadcrumbTag: {
    margin: 0,
    cursor: 'pointer',
    fontSize: 'var(--font-size)',
    padding: 'var(--x1) var(--x3)',
  },
  filterCloseBadge: {
    display: 'none',
    backgroundColor: 'var(--color-primary-10)',
    color: 'var(--color-primary-1)',
    width: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    cursor: 'pointer',
    zIndex: 9,
    '&:focus, &:hover, &:active': {
      display: 'flex',
    },
    '&:hover': {
      backgroundColor: 'var(--color-primary-9)',
    },
  },
});

export const cardBodyStyle = {
  boxShadow: 'var(--box-shadow-menu)',
  borderRadius: 'var(--radius-base)',
  padding: 'var(--x4)',
  maxHeight: 'max(calc(100vh - 300px), 400px)',
  overflow: 'auto',
};
